
---
- name: Install Apache and Update my Home Page
  hosts: all
  become: yes

  vars:
    sourse_file: ./index.html
    destin_file: /var/www/html

  tasks: 

  - name: Check and Print LINUX Version
    debug: var=ansible_os_family

  - name: Install Apache Web Server for Ubuntu
    apt: name=apache2 state=latest
    when: ansible_os_family == "Debian"

  - name: Install Apache Web Server for RedHat
    yum: name=httpd state=latest
    when: ansible_os_family == "RedHat"

  - name: Copy HomePage file to Web Server
    copy: src={{ sourse_file }} dest={{ destin_file }} mode=0555
#   notify: Restart Apache 

  - name: Start Web Server service 
    service: name=apache2 state=started enabled=yes
    when: ansible_os_family == "Debian"

  - name: Start Web Server for RedHat
    service: name=httpd state=started enabled=yes
    when: ansible_os_family == "RedHat"

  handlers:
  - name: Restart Apache for Debian
    service: name=apache2 state=restart

  handlers:
  - name: Restary Apache for RedHat
    service: name=httpd state=restart
  
 
